version: 2

workflows:
  version: 2
  build:
    jobs:
      - backend
      - web

jobs:
  backend:
    docker:
      - image: circleci/openjdk:11-jdk-sid

    steps:
      - checkout

      - restore_cache:
          key: futbolin-backend-{{ .Branch }}-{{ checksum "backend/pom.xml" }}

      - run:
          name: Prepare build
          command: mvn -f backend/pom.xml dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: futbolin-backend-{{ .Branch }}-{{ checksum "backend/pom.xml" }}

      - run:
          name: Build software
          command: |
            mvn -f backend/pom.xml \
              clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar \
              -Dsonar.projectKey=mthmulders_futbolin \
              -Dsonar.organization=mthmulders-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_LOGIN

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
    
      - store_test_results:
          path: ~/junit
  web:
    docker:
      - image: circleci/node:10.15.0-stretch

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Installing Azure CLI
          command: |
            echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ stretch main" | \
                sudo tee /etc/apt/sources.list.d/azure-cli.list
            curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
            sudo apt-get install apt-transport-https
            sudo apt-get update
            sudo apt-get install azure-cli
      - run:
          name: Login to Azure Container Registry
          command: |
            mkdir -p ~/.azure
            cat << EOF > ~/.azure/config
            [core]
            output = table
            collect_telemetry = no

            [logging]
            enable_log_file = no

            [defaults]
            location = westeurope
            EOF

            az login --service-principal -u $AZ_SP_URL -p $AZ_SP_PASSWORD --tenant $AZ_SP_TENANT --allow-no-subscriptions
            az acr login --name FutbolinRegistry

      - run:
          name: Build container
          command: |
            pushd web
            ./build-container.sh