version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "14 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-sid
    steps:
      - checkout
      - restore_cache:
          key: futbolin-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Prepare build
          command: mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: futbolin-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Build software
          command: |
            mvn \
              clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar \
              -Dsonar.projectKey=mthmulders_futbolin \
              -Dsonar.organization=mthmulders-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_LOGIN
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
