version: 2

workflows:
  version: 2
  build:
    jobs:
      - backend
      - web
  nightly:
    triggers:
      - schedule:
          cron: "14 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - backend
      - web

jobs:
  backend:
    docker:
      - image: circleci/openjdk:11-jdk-sid
    steps:
      - checkout
      - restore_cache:
          key: futbolin-backend-{{ .Branch }}-{{ checksum "backend/pom.xml" }}
      - run:
          name: Prepare build
          command: mvn -f backend/pom.xml dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
            - ~/.sonar/cache
          key: futbolin-backend-{{ .Branch }}-{{ checksum "backend/pom.xml" }}
      - run:
          name: Build software
          command: |
            mvn -f backend/pom.xml \
              clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar \
              -Dsonar.projectKey=mthmulders_futbolin \
              -Dsonar.organization=mthmulders-github \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_LOGIN
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
  web:
    docker:
      - image: circleci/node:10.15.0-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Azure Container Registry
          command: |
            docker login futbolin.azurecr.io -u $AZ_SP_ID -p $AZ_SP_PASSWORD
      - run:
          name: Build container
          command: |
            pushd web
            ./build-container.sh $CIRCLE_BUILD_NUM