version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: dotnet restore src/
      - run: dotnet build src/
      - run: dotnet test --no-build src/Seedwork.Test