apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: futbolin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: mthmulders-docker-futbolin.bintray.io/futbolin-webapp
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
            - containerPort: 9443
          env:
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: webapp
                  key: oid.client.id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: webapp
                  key: oid.client.secret
            - name: CLIENT_KEYSTORE_FILE
              value: /tmp/keystore.p12
            - name: CLIENT_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webapp
                  key: oid.keystore.password
            - name: OIDC_RPHOSTANDPORT
              value: https://futbolin.mulders.it/
      volumes:
      - name: client-keystore
        secret:
          secretName: webapp
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: futbolin
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9080
    targetPort: 9080
  - name: https
    port: 9443
    targetPort: 9443
  selector:
    app: webapp

---

apiVersion: v1
kind: Secret
metadata:
  name: webapp
  namespace: futbolin
type: Opaque
data:
  # OpenID Connect Client ID
  oid.client.id: ""
  # OpenID Connect Client Secret
  oid.client.secret: ""
  # OpenID Connect Client keystore password
  oid.keystore.password: ""
