apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: futbolin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: mthmulders-docker-futbolin.bintray.io/futbolin-webapp
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
            - containerPort: 9443
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: futbolin
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9080
    targetPort: 9080
  - name: https
    port: 9443
    targetPort: 9443
  selector:
    app: webapp